pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
               echo "Building right now"
            }
        }

        stage("Test") {
            steps {
               echo "Testing process"
            }
        }
    }
}